name: flutter_smooth_scroll_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  adaptive_dialog: ^2.1.0
  blur: ^3.1.0
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pedantic_mono: ^1.24.0+1

flutter:
  uses-material-design: true
